# This is a basic workflow to help you get started with Actions

name: Download Chromium

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # 每 8 小时运行一次
    - cron: "0 */8 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Download Chromium
        run: |
          wget https://download-chromium.appspot.com/dl/Win?type=snapshots -T 20 -O Win.zip
          wget https://download-chromium.appspot.com/dl/Win_x64?type=snapshots -T 20 -O Win_x64.zip
          wget https://download-chromium.appspot.com/dl/Mac?type=snapshots -T 20 -O Mac.zip
          wget https://download-chromium.appspot.com/dl/Mac_Arm?type=snapshots -T 20 -O Mac_Arm.zip
          wget https://download-chromium.appspot.com/dl/Linux?type=snapshots -T 20 -O Linux.zip
          wget https://download-chromium.appspot.com/dl/Linux_x64?type=snapshots -T 20 -O Linux_x64.zip
          wget https://download-chromium.appspot.com/dl/Linux_ChromiumOS_Full?type=snapshots -T 20 -O Linux_ChromiumOS_Full.zip
          wget https://download-chromium.appspot.com/dl/Android?type=snapshots -T 20 -O Android.zip

      - name: Setup Python
        uses: actions/setup-python@v3.0.0
  
      - name: Push
        run: |
          date +"%Y-%m-%d %H:%M:%S" > update.txt
          git config --global user.email "2071916845@qq.com"
          git config --global user.name "it985"
          #git add .
          #git commit -m $(date +"%Y-%m-%d_%H:%M:%S")
          #git remote set-url origin https://${{ github.actor }}:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
          #git push origin main
          #npm version patch
          #npm publish
          python upload.py
          rm -r *.zip
          git add .
          git commit -m $(date +"%Y-%m-%d_%H:%M:%S")
          git push origin main
        #env:
         # NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 7
          keep_minimum_runs: 6
